# Mouse
CONFIG_ZMK_POINTING=y
# NKRO
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
CONFIG_ZMK_HID_KEYBOARD_NKRO_EXTENDED_REPORT=y
# Bluetooth
CONFIG_BT_BAS=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y
CONFIG_BT_SMP_MIN_ENC_KEY_SIZE=16
